[package]

name = "scan-rules"
version = "0.0.1"
authors = ["Daniel Keep <daniel.keep@gmail.com>"]

[features]
"tuples-16" = []
"arrays-32" = []

[dependencies]
itertools = "0.4.0"
lazy_static = "0.1.14"
regex = "0.1.41"
strcursor = "0.2.1"
